#!/usr/bin/env python3
"""
Cross-Agent Context Bridge - LLM-powered context transfer between agents.
Called by: agents bridge <session> [--to codex|claude] [--format md|json]
Env vars: SESSION_KEY, TARGET_AGENT (claude/codex), FORMAT (md/json), OUTPUT
"""

import os
import sys
import json
import time
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from adapters.claude import ClaudeAdapter
from adapters.codex import CodexAdapter

from utils import (WHITE, CYAN, GREEN, YELLOW, MAGENTA, BLUE, GRAY, RED, BOLD, DIM, R,
                   CACHE_DIR, resolve_session as _resolve_session, extract_text_from_record)
from llm import get_llm, LLMError, ANTHROPIC_SMALL, ANTHROPIC_LARGE, OPENAI_SMALL, OPENAI_LARGE
from schemas import BridgeOutput

ALL_ADAPTERS = [ClaudeAdapter(), CodexAdapter()]

BRIDGE_DIR = os.path.join(CACHE_DIR, "bridges")

session_key = os.environ.get("SESSION_KEY", "")
target_agent = os.environ.get("TARGET_AGENT", "")
fmt = os.environ.get("FORMAT", "md")
output = os.environ.get("OUTPUT", "")


def resolve_session():
    fpath, agent_name, project, _sid = _resolve_session(session_key, ALL_ADAPTERS)
    return fpath, agent_name, project


def extract_session_data(fpath, agent_name):
    """Extract structured data from session for the handoff prompt."""
    messages = []
    files_modified = {}
    commands = []
    current_task = ""
    git_branch = ""

    try:
        with open(fpath) as f:
            for line in f:
                try:
                    record = json.loads(line)

                    # Git branch
                    if record.get("gitBranch") and not git_branch:
                        git_branch = record["gitBranch"]

                    role, text = extract_text_from_record(record, agent_name)
                    if role and text:
                        messages.append({"role": role, "text": text})
                        if role == "user" and not current_task:
                            current_task = " ".join(text.split())[:200]

                    # Extract tool usage from Claude assistant messages
                    if agent_name == "claude" and record.get("type") == "assistant":
                        content = record.get("message", {}).get("content", [])
                        if isinstance(content, list):
                            for item in content:
                                if isinstance(item, dict) and item.get("type") == "tool_use":
                                    name = item.get("name", "")
                                    inp = item.get("input", {})
                                    if name in ("Write", "Edit"):
                                        fp = inp.get("file_path", "")
                                        if fp:
                                            files_modified[fp] = files_modified.get(fp, 0) + 1
                                    elif name == "Bash":
                                        cmd = inp.get("command", "")
                                        if cmd:
                                            commands.append(cmd[:100])

                except (json.JSONDecodeError, KeyError, TypeError):
                    pass
    except OSError:
        pass

    return {
        "messages": messages,
        "files_modified": files_modified,
        "commands": commands,
        "current_task": current_task,
        "git_branch": git_branch,
    }


def format_markdown(handoff, source_agent, project, session_id, target):
    """Format handoff as markdown document."""
    lines = []
    lines.append("# Context Handoff")
    lines.append("")
    lines.append(f"**From:** {source_agent} session `{session_id[:8]}`")
    lines.append(f"**To:** {target}")
    lines.append(f"**Project:** {project}")
    lines.append(f"**Generated:** {datetime.utcnow().isoformat()}Z")
    lines.append("")

    lines.append("## Summary")
    lines.append(handoff.handoff_summary)
    lines.append("")

    lines.append("## Current State")
    lines.append(handoff.current_state)
    lines.append("")

    if handoff.next_steps:
        lines.append("## Next Steps")
        for i, step in enumerate(handoff.next_steps, 1):
            lines.append(f"{i}. {step}")
        lines.append("")

    if handoff.important_context:
        lines.append("## Important Context")
        for ctx in handoff.important_context:
            lines.append(f"- {ctx}")
        lines.append("")

    if handoff.files_to_review:
        lines.append("## Files to Review")
        for f in handoff.files_to_review:
            lines.append(f"- `{f}`")
        lines.append("")

    if handoff.warnings:
        lines.append("## Warnings")
        for w in handoff.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by agents bridge*")
    return "\n".join(lines)


def format_json(handoff, source_agent, project, session_id, target):
    """Format handoff as structured JSON."""
    return json.dumps({
        "handoff": {
            "from_agent": source_agent,
            "to_agent": target,
            "session_id": session_id,
            "project": project,
            "generated": datetime.utcnow().isoformat() + "Z",
        },
        "summary": handoff.handoff_summary,
        "current_state": handoff.current_state,
        "next_steps": handoff.next_steps,
        "important_context": handoff.important_context,
        "files_to_review": handoff.files_to_review,
        "warnings": handoff.warnings,
    }, indent=2)


def cmd_bridge():
    global target_agent

    if not session_key:
        print(f"{RED}Usage: agents bridge <session> [--to claude|codex] [--format md|json]{R}")
        raise SystemExit(1)

    llm = get_llm()
    if not llm.available():
        print(f"{RED}No LLM API key found.{R}")
        print(f"{DIM}Set ANTHROPIC_API_KEY or OPENAI_API_KEY to enable bridging.{R}")
        raise SystemExit(1)

    fpath, agent_name, project = resolve_session()
    if not fpath or not os.path.isfile(fpath):
        print(f"{RED}Could not find session: {session_key}{R}")
        raise SystemExit(1)

    session_id = os.path.basename(fpath).replace(".jsonl", "")

    if not target_agent:
        target_agent = "codex" if agent_name == "claude" else "claude"

    print(f"{BOLD}{CYAN}Context Bridge{R}")
    print(f"{DIM}{'─' * 52}{R}")

    a_color = CYAN if agent_name == "claude" else GREEN
    t_color = CYAN if target_agent == "claude" else GREEN

    print(f"  {a_color}[{agent_name}]{R} {WHITE}{session_id[:8]}{R}  →  {t_color}[{target_agent}]{R}")
    print(f"  {BLUE}{project}{R}")
    print()

    # Extract session data
    data = extract_session_data(fpath, agent_name)

    print(f"  {DIM}Extracted: {len(data['messages'])} messages, "
          f"{len(data['files_modified'])} files, {len(data['commands'])} commands{R}")
    print(f"  {DIM}Generating handoff briefing...{R}", flush=True)

    # Build key messages for the prompt (last 10 user messages, truncated)
    user_messages = [m["text"][:200] for m in data["messages"] if m["role"] == "user"][-10:]

    # LLM handoff generation
    try:
        model = ANTHROPIC_LARGE if llm.provider == "anthropic" else OPENAI_LARGE
        raw = llm.render_and_call_json("bridge_handoff", {
            "source_agent": agent_name,
            "target_agent": target_agent,
            "project": project,
            "current_task": data["current_task"],
            "git_branch": data["git_branch"],
            "key_messages": user_messages,
            "files_modified": data["files_modified"],
            "commands": data["commands"][-15:],
        }, model=model, max_tokens=1536, temperature=0.3)
        handoff = BridgeOutput.from_dict(raw)
    except LLMError as e:
        print(f"  {RED}Handoff generation failed: {e}{R}")
        raise SystemExit(1)

    # Format output
    if fmt == "json":
        result = format_json(handoff, agent_name, project, session_id, target_agent)
    else:
        result = format_markdown(handoff, agent_name, project, session_id, target_agent)

    # Save
    if output and output != "-":
        with open(output, "w") as f:
            f.write(result)
        print(f"\n{GREEN}Bridge document saved: {output}{R}")
        bridge_file = output
    else:
        os.makedirs(BRIDGE_DIR, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        ext = "json" if fmt == "json" else "md"
        bridge_file = os.path.join(BRIDGE_DIR, f"bridge-{session_id[:8]}-to-{target_agent}-{timestamp}.{ext}")
        with open(bridge_file, "w") as f:
            f.write(result)
        print(f"\n{GREEN}Bridge document saved:{R}")
        print(f"  {WHITE}{bridge_file}{R}")

    # Show summary
    print()
    print(f"  {WHITE}Summary:{R} {handoff.handoff_summary[:100]}")
    print(f"  {WHITE}State:{R}   {handoff.current_state[:100]}")
    if handoff.next_steps:
        print(f"  {WHITE}Next:{R}    {handoff.next_steps[0]}")
    if handoff.warnings:
        print(f"  {YELLOW}Warning:{R} {handoff.warnings[0]}")

    print()
    print(f"{DIM}Use this to start a new {target_agent} session with context:{R}")
    print(f'{DIM}  cd "{project}" && {target_agent} "Read {bridge_file} for context, then continue the work"{R}')
    print()
    llm.print_cost_summary()


if __name__ == "__main__":
    cmd_bridge()
